### ISSUE TITLE
Feature request: Ability to make several instances of Scratchpad point to the same directory for txt-files

### ISSUE THREAD

**Issue by DrGonzo94** [rkusa/dcs-scratchpad#12]
Hi! Thanks for a wonderful mod!

I have two instances of DCS, an open beta and a stable one. I would like to use the same scratchpad library of txt files for both of them. This functionality doesn't seem to exist currently. 

Kind regards

**Comment by rkusa** [comment]
Hi, thanks for the feature request! You should be able to solve this use-case without Scratchpad having to directly support it. You could create a symbolic link between your following two folders: `Saved Games\DCS.openbeta\Scratchpad` and `Saved Games\DCS\Scratchpad`. The keywords _windows create symlink directory_ should get you the instructions on how to create such a symbolic link. Does this work for you?

**Comment by DrGonzo94** [comment]
Yes, I'm sure it would, thank you. 

I'm not a big fan of symbolic links in Windows, and while I don't understand the mechanics of hooks and DCS scripts, it seems like both SRS and Tacview supports several installations without much effort. No worries tho, if it becomes more pressing, I'll try the symbolic link solution!

Kind regards

**Comment by kaltokri** [comment]
I use symlinks for scratchpad, screenshot, mission and input folder and it works fine.

**Comment by chazmat** [comment]
I can confirm that this works!
Cheers!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rkusa** [comment]
Closing for now, as symlinks seem to be a reasonable good solution
