### ISSUE TITLE
Feature Request: add coords in DMS, DM and DD

### ISSUE THREAD

**Issue by wraith70** [rkusa/dcs-scratchpad#14]
Love scratchpad.  Ideal for VR.
A feature request.  DCS uses 3 different L/L formats:

DMS - For the F/A-18C, coordinates are formatted as DD°MM'SS.ss"
DM - For the F-16C, coordinates are formatted as DD°MM.mmm'
DD - For the M2000C, coordinates are formatted as DD.MM.mm

Currently only DMS.  Could the other 2 formats be included?
Thanks,
Wraith

**Comment by rkusa** [comment]
Hi Wraith, that is a good suggestion! Since I don't want to add complexity by adding a single button for each format, I'd probably look into whether I can get the aircraft type of the player and automatically adjust the format accordingly.

**Comment by wraith70** [comment]
That's one way, or you can just print all 3 and we can copy and paste the one that is relevant.

**Comment by rkusa** [comment]
Thanks for checking and confirming 👍 
I've extended the implementation to [select the format based on the player's aircraft ](https://github.com/rkusa/dcs-scratchpad/blob/master/Scripts/Hooks/scratchpad-hook.lua#L264-L265) (not released yet, but will be in the next version).
