### ISSUE TITLE
Font/Display Issue

### ISSUE THREAD

**Issue by bradley-r** [rkusa/dcs-scratchpad#15]
I stumbled across scratchpad while trawling the forums the other day, and I'm surprised I hadn't seen or heard of it before! Our wing plans to put it to good use; one already has it installed and working.

My problem arises from my choice of OS; I'm one of (the presumed) few who run DCS on Linux - my previous GitHub contributions make that _rather clear!_ Now, DCS doesn't _know_ this; it recognises a normal Windows file structure) but some things do require some tinkering. It seems scratchpad falls within this group, as while it loads and functions as expected (appears, can be toggled on/off and saves content), actually typing in-game doesn't change the entry field. I know it _is_ working - the content can be viewed in `0000.txt` after the fact, and the lua is loaded in the log - but the text doesn't appear. Is there a set font and/or directory that is read to style the text? If so, I can try to install it and see if the text shows as expected.

Don't worry if not; I understand I'm certainly in the minority of both scratchpad and DCS users, and bear the consequences of running in an _unsupported_ environment. My thanks for the work that has gone into this tool.

**Comment by rkusa** [comment]
Thanks for the report. I'd be happy in helping making it work on Linux (since I can totally relate to wanting to use Linux over Windows).

> Is there a set font and/or directory that is read to style the text? If so, I can try to install it and see if the text shows as expected.

I think you are on a good track already. The font used for displaying is `CONSOLA.TTF`. Maybe installing it, or changing it to another font does fix the issue? The font is set here: https://github.com/rkusa/dcs-scratchpad/blob/master/Scripts/Scratchpad/ScratchpadWindow.dlg#L172

**Comment by bradley-r** [comment]
> The font is set here: https://github.com/rkusa/dcs-scratchpad/blob/master/Scripts/Scratchpad/ScratchpadWindow.dlg#L172

If only I looked into the `.dlg` instead of the `.lua` file! Changing `CONSOLA.TTF` to `CALIBRI.TTF` (or any other installed font) did the trick. Thanks again!
