### ISSUE TITLE
Feature request: Hotkey for "+ L/L" button

### ISSUE THREAD

**Issue by juliancastroorozco** [rkusa/dcs-scratchpad#19]
To add a hotkey for the "+ L/L" button, in VR moving the mouse to the right GPS location plus then moving it to the "+ L/L" is a bit troublesome, and a feature like this will help.

**Comment by iLIttleNose** [comment]
a hotkey might be nice to enable use with something like VoiceAttack

**Comment by Ysasmendi** [comment]
Can we bind the main window to Hotas?

**Comment by OloRatuj** [comment]
3 new hotkeys were created and waiting in this merge request https://github.com/rkusa/dcs-scratchpad/pull/29 for your approval @rkusa.

**Comment by rkusa** [comment]
Added with #29, thanks again @OloRatuj
