### ISSUE TITLE
Feature Request: ability to assign specific modifiers (e.g. L_CTRL, R_SHIFT) to hotkey

### ISSUE THREAD

**Issue by HomeFries94** [rkusa/dcs-scratchpad#2]
Brilliant plugin for DCS.  I was wondering if it would be feasible to be able to specify specific modifiers such as left control or right shift to the hotkey.  For people who use different key combinations for programmable controllers or full cockpits, this would be huge for flexibility.

Additionally, I wouldn't mind seeing the ability to assign DirectX buttons to the hotkey, though due to the keyboard nature of the plugin this is may not be worth the effort.

**Comment by rkusa** [comment]
Hi, have you tried e.g. `LCTRL` instead of `CTRL` for the hotkey config? (I haven't, yet)
I'd really like to have the configuration of the keybinding in the keybinding settings of DCS (which would allow using directx buttons as well), but I haven't investigated this option yet.

**Comment by HomeFries94** [comment]
`    ["hotkey"] = "LCtrl+LShift+x",` did not work.

Is there a reference for the proper key nomenclature in lua?

**Comment by rkusa** [comment]
Thanks for testing. I had a look into the lua source of DCS and it seems that there is only `ctrl` and no distinction between left and right `ctrl`  :-/

**Comment by rkusa** [comment]
Closing as not possible. If anyone knows how I can get the Scratchpad hotkeys into the regular key binding settings of DCS, please let me know
