### ISSUE TITLE
Cant move window

### ISSUE THREAD

**Issue by ozdeadmeat** [rkusa/dcs-scratchpad#21]
Ages ago i accidentally moved the scratchpad window to the top of my screen. I just deleteed and replaced the files for scratchpad but the position still persists. Is there a config file i can delete to reset the position to defaults?

**Comment by rkusa** [comment]
@ozdeadmeat you can delete `Saved Games\DCS\Config\ScratchpadConfig.lua` to reset everything to default

**Comment by ozdeadmeat** [comment]
Thanks mate
