### ISSUE TITLE
can't open in VR (quest2) [close]

### ISSUE THREAD

**Issue by docbrownd** [rkusa/dcs-scratchpad#23]
Hi, 
i love this mod and in classicle game there is no problem. 
But when i play in VR (with a quest2), nothing happens when i press ctrl+shift+ => the window doesn't open :s 

Any idear why ?

thanks

**Comment by rkusa** [comment]
Hi, the windows is most probably outside of your viewport in VR. Try either to:
- move the the scratchpad to the left (middle or top) in non-VR, or
- delete `Saved Games\DCS.openbeta\Config\ScratchpadConfig.lua` to reset its position.

Does that help?

**Comment by docbrownd** [comment]
only shit it works ^^ 
I move the window in middle in non-VR and now i see it in VR.

thanks
