### ISSUE TITLE
Selecting scratchpad in VR is...  iffy?

### ISSUE THREAD

**Issue by KevyKevTPA** [rkusa/dcs-scratchpad#24]
I've been able to select the scratchpad while in VR, but it seems more luck than anything else.  No issues on the map, but is there some secret to grabbing it in VR?

**Comment by rkusa** [comment]
You kinda have two different cursors in VR in DCS. From the top of my head, I think one is a white dot, and the other one a bluish cross. The difficulty, they are usually at different locations. So you'd have to move your mouse around until you see the white dot, which is the one that allows interacting with the Scratchpad. IIRC, the white dot is only visible as long as you have a UI element like the chat or Scratchpad open.
