### ISSUE TITLE
New Commit broke return nil under coordsType()

### ISSUE THREAD

**Issue by Wamwod** [rkusa/dcs-scratchpad#26]
Issue is in Title.
Line in question https://github.com/rkusa/dcs-scratchpad/blob/main/Scripts/Hooks/scratchpad-hook.lua?#L291
Basically causing Aircraft not in the list under coordsType or spectator to no longer return coordinates into scratchpad window when +L/L is pressed.
I don't specifically know what's causing this issue, my temporary fix is to just use ` return {DMS = true, DDM = true, MGRS = true}` though I don't think that's how it should be done IMO i believe there's something more elegant but I just can't think/find it.

**Comment by rkusa** [comment]
I'll look into it, thanks for the report!

**Comment by rkusa** [comment]
It was caused by trying to read a property from `nil`, eg in:
```
formatCoord("DMS", true, lat, type.DMS)
                                  ^
                                  |
```

Since handling this is quite ugly, I actually prefer your solution of `return {DMS = true, DDM = true, MGRS = true}`, which is the one I commited as a fix.
