### ISSUE TITLE
Feature request: mouse click to remove focus

### ISSUE THREAD

**Issue by OR-WS** [rkusa/dcs-scratchpad#28]
Similar to how a mouse click **in** the scratchpad window transfers focus to the scratchpad , it would be very convenient if a mouse click anywhere outside of the scratchpad -so in the game world- would transfer focus back to the game as opposed to having to use Esc. Somehow hitting Esc to achieve this (in part because Esc is the default key to bring up the options/close menu in DCS) is less intuitive than quickly clicking anywhere.

**Comment by Jeffb4u** [comment]
Yah I have found reaching for the ESC key not the best when flying, i kinda have to hit it several times also to get the resume menu up then i know i have focus on the game.  A mouse click outside would be easier.  So many times i have left focus in the pad and hit a button that results in overwriting the whole text and saving it.  Tab for example to open your email (text message envelope) seems to highlight all the text in the pad and the very next button press boom its all gone.  I use the Thrustmaster Target software so most of my Hotas controls are keybinds - This in itself isnt an issue but being sure Focus is on the game and not the pad is critical - for example if i do a case 3 i use the pad to jot BRC DME and pushtime - if i then say hit hook down lights on etc while focus is on the pad it usually means boom all the text has gone with maybe an H or L left behind - TLDR the guy above idea is a good one.....

**Comment by rkusa** [comment]
I agree, this would be a very useful behaviour. However, DCS doesn't seem to provide me any way to detect clicks outside of the Scratchpad. I observed the same behaviour for the multiplayer chat.

I only have the following two ideas:

1. Open a bug report in the DCS forum requesting this behaviour for the multiplayer chat (this way Scratchpad gets it automatically, or I can later check how they've done it for the chat).

2. Add an invisible window behind the Scratchpad that spans the whole screen. Upon clicking it, the focus from the scratchpad as well as the invisible window is removed. This has one major drawback though. Right now, if you click a cockpit element while the Scratchpad has the focus, the focus is already removed and the click interacts with the cockpit element right away. With this invisible window, you'd have to click twice to be able to interact with the cockpit: once to remove the focus, and then once again for the actual interaction with the cockpit (it also wouldn't give you any tooltip for the cockpit while the Scratchpad has focus).

**Comment by OR-WS** [comment]
Appreciate you chipping in and trying to think of solutions.

Little out of the box: is it possible to detect whether the mouse cursor is inside the scratchpad and use that for focus? So mouse inside the window means focus on the scratchpad, mouse outside of it or scratchpad toggled OFF means focus on DCS. Without losing the current ability to set the size of the scratchpad.

**Comment by rkusa** [comment]
> Little out of the box: is it possible to detect whether the mouse cursor is inside the scratchpad and use that for focus? So mouse inside the window means focus on the scratchpad, mouse outside of it or scratchpad toggled OFF means focus on DCS. Without losing the current ability to set the size of the scratchpad.

This might be possible. I'd be concerned though that this behaviour would be unexpected for a lot of users and thus lead to a lot of confusion.

You can btw remove the focus from the text field by clicking the header of the Scratchpad. This way you can remove the focus with the mouse and don't have to reach for Esc. Does this maybe help a little already?

A pure visual improvement could be that I change the header color of the Scratchpad while the text field has focus. This way you'd have a better visual aid that the focus inside the Scratchpad.

**Comment by rkusa** [comment]
Nevermind, found a way. I'll release a new version soon. Until then you can also download the current development version here: https://github.com/rkusa/dcs-scratchpad/archive/refs/heads/main.zip

**Comment by Jeffb4u** [comment]
Sweet This is great work many thx... - The idea of changing the header tape colour to indicate focus may help also as long as it is subtle.  But otherwise jolly good show.
