### ISSUE TITLE
Feature Request: Ability to create entry from current coodinates under mouse from MapView

### ISSUE THREAD

**Issue by joaomcarlos** [rkusa/dcs-scratchpad#3]
Hi,

This would be a killer feature, the ability for when left clicking on the map with a hotkey pressed, something like alt+left click, have the current coordinates copied over to the scratch pad at the bottom, one coordinate per line.

We would be able to go to the map, find a location and left click on it to get the coordinates into the scratchpad.

Support for this feature : https://forums.eagle.ru/showthread.php?t=216559

**Comment by rkusa** [comment]
Great idea! I don't think a mod can do that, but I'll still investigate a bit

**Comment by HomeFries94** [comment]
I'd love it too, but this level of integration involves DCS export and goes well beyond a "simple" overlay.

* "Simple" is not an insult or slight, but just a recognition of scope in that the utility as is does not require exports.

**Comment by rkusa** [comment]
I've added a feature that allows importing the coords of all F10 mark labels into the Scratchpad. However, it will only work in single-player (or if your client is also the server). A solution that also works in multi-player seems to be https://github.com/Santi871/DCSWaypointEditor
