### ISSUE TITLE
UI simplification

### ISSUE THREAD

**Issue by speed-of-heat** [rkusa/dcs-scratchpad#33]
Why the checkbox for +L/L it's just another step in the UI, which makes it more awkward to use.  Does it fix some other bug?  can we have a config option just to have +L/L available all the time?

**Comment by rkusa** [comment]
Thanks for the feedback. I agree that it would be cool to not have this extra step. The reason for it is that I cannot detect when the F10 map is open. So if I'd remove the checkbox, the white dot in the middle would always be visible, even outside of the F10 map (so basically in the cockpit as well).
