### ISSUE TITLE
How to add waypoint to NS430?

### ISSUE THREAD

**Issue by Handsome1080P** [rkusa/dcs-scratchpad#36]
I can't understand the readme,need modiy the files?Can't add waypoint realtime?

**Comment by rkusa** [comment]
I am not really sure what else I can add to what it is written in the README. Maybe try asking in https://forum.dcs.world/topic/195700-in-game-scratchpad-mod-available-works-great-in-vr with a bit more specific information what you don't understand from the steps provided in the README?

**Comment by Handsome1080P** [comment]
> I am not really sure what else I can add to what it is written in the README. Maybe try asking in https://forum.dcs.world/topic/195700-in-game-scratchpad-mod-available-works-great-in-vr with a bit more specific information what you don't understand from the steps provided in the README?

Thx,I found this repo in GitHub,so don't know u had posted in ED fourm.
