### ISSUE TITLE
Mission Editor problems

### ISSUE THREAD

**Issue by mitchelr** [rkusa/dcs-scratchpad#38]
Scratchpad works fine in-game but if I use it in Mission Editor the buttons to interact don't show up at the bottom.  I can still use it but cant get the locale data.

**Comment by mitchelr** [comment]
This is normal behavior of the app.

**Comment by rkusa** [comment]
Yes, for anyone else finding this issue: The checkbox and +L/L are not shown in the menu and mission editor, because the APIs to make them work don't work there. The APIs only work when you are in an actual mission.

**Comment by mitchelr** [comment]
Thanks mate for all the work getting this out it has made a tremendous difference.
