### ISSUE TITLE
Small error in DDM lat/lon

### ISSUE THREAD

**Issue by aeronautes** [rkusa/dcs-scratchpad#41]
There is a small error in the lat/lon for DDM modules such as F16. It's a result of how DCS converts DDM. I believe DCS converts at a higher order of precision and simply truncates to 3 decimal digits. scratchpad however uses format() to round floats to 3 with values rounded to the nearest thousands. This will only show up in cases where values are rounded up so its appearance is intermittent, dependent on the location for either lat or lon.

Repro:
On syria map with F16 go to F10 map and at north end of Beirut runway 16.
Center the L/L dot to  
N 33°50.527, E 35°28.667

Can use an object or mouse cursor to verify location. Then click +L/L button and notice the result is off by .001 for both lat and lon.
N 33°50.528', E 035°28.668'                                                     
36 S YC 29269 47413                                                                
8m, 26ft                                                                           

The error of .001' can equate to upwards of 12 feet error. The proposed fix is just to increase format() precision by 1 digit and then truncate the extra digit.

**Comment by rkusa** [comment]
Thanks for the report. I can confirm that I can see the difference, and I also think DCS is truncating while Scratchpad is rounding. However, I'd expect the rounding to be more precise. I did a non-scientific test to confirm (I really only tested twice, so the result could still be in the margin of error for JDAMs):

![Screen_221029_104656](https://user-images.githubusercontent.com/409021/198822602-afd818ff-37a1-45e8-96f9-b15ee8b5e807.jpg)

Coordinates are for the windsock. The blue crater is from a JDAM employment using the rounded coordinates, while the red one is from using the truncated coordinates from the DCS map. Again, could be still coincidental and caused by the margin of error from employing JDAMs.

**Comment by aeronautes** [comment]
I looked more into this and found better way to illustrate the behavior. In summary the rounding approach shifts the coords half the diagnal length, inducing up to 4feet error. Using the patch, scratchpad gives results consistent with F10.

Included below is a mission with flags to show the range of physical locations with the extent of N42 14.580' E42 02.022' (80/22). In this image North is up and the white flags indicate the region that F10 maps considers 80/22. The bottom left white flag is where the TGP will point at with those coords. The next higher coord for F10(81/23) is just above/right of the top right white flag.

![Screen_221031_111221](https://user-images.githubusercontent.com/106369160/199099417-6b416d07-4d6b-4b50-8d5f-f32c2cd837ef.jpg)

![Screen_221031_041225](https://user-images.githubusercontent.com/106369160/199099861-dbfb53bd-ff62-4431-9249-3b47cfdb4bae.jpg)

![Screen_221031_041239](https://user-images.githubusercontent.com/106369160/199100053-92e78b4a-e5c3-460a-ad40-d6ab7482aa12.jpg)

The red flags indicate where scratchpad indicates 80/22. Essentially the difference is the rounding produces values that are centered around the DCS location rather than origin centric(lower left). DDM has a builtin error margin of 7feet from the .001' resolution. The rounding of DDM potentially adds 4feet of error, totalling 11feet between where scratchpad indicates 80/22 vs where  F10 indicates 80/22. Using the truncation method produces results that align with F10/TGP. I tried to add an extra set of flags to show the area but they were so close to the white F10 flags, that they became obscured.
![Screen_221031_112802](https://user-images.githubusercontent.com/106369160/199102828-41b4e56c-bcd3-425a-bd59-10757d872c39.jpg)

Using a LGB at 4k altitude and 350kts provides a very consistent and precise bomb delivery method. Doing this, produced accuracy at the sub .001' resolution that is highly reproducable. This image shows 2 bombs at waypoint 1, lower left white flag and 2 bombs at waypoint 2, upper right. These are consistent across 10 different strikes. 
![Screen_221031_040704](https://user-images.githubusercontent.com/106369160/199101432-085e9393-7892-4e68-9944-d644e3a09a2f.jpg)

The conclusion is that there are two consequences with the current scratchpad behavior. Bombs can potentially land an extra 4feet away for a total of 11ft error from a target. And the second is the users may notice the discrepency and the required explanation of why scratchpad gives a different result from F10/TGP coords.

The following file is droptest.miz. But because github didnt like the file extension I renamed to zip. Download and rename to droptest.miz to open in DCS.
[droptest-mizrename.zip](https://github.com/rkusa/dcs-scratchpad/files/9904119/droptest-mizrename.zip)

**Comment by aeronautes** [comment]
On review I think you're right that rounding produces coords with a smaller average and maximum error by using the centroid of the .001' coord. DCS instead is origin centered. There is still the issue of discrepency for the user which would be confusing. But it may be a suitable exchange for the better accuracy.

**Comment by rkusa** [comment]
> On review I think you're right that rounding produces coords with a smaller average and maximum error by using the centroid of the .001' coord.

@aeronautes With that, I'll be lazy an skip reading your second last comment. Thanks for the effort you put into it! I can live with the user confusion. Let me know if you end up having any additional thoughts regarding this topic.
