### ISSUE TITLE
2.8 Update - + L-L Issue pulling coords from F10

### ISSUE THREAD

**Issue by habibivoodoo** [rkusa/dcs-scratchpad#43]
DCS 2.8 update has broken the ability to pull coords from the f10 map

**Comment by docbrownd** [comment]
Hi, you just need to add Terrain definition

Add this line :

`Terrain = require('terrain')`

at the begining of the scratchpad.lua file

**Comment by habibivoodoo** [comment]
in the scratchpad-hook.lua? Thank You for your help

**Comment by tidefall** [comment]
This fixes the issue for me and 2 others I had test this. In "Hooks/scratchpad-hook.lua" add line at the top.

```
local function loadScratchpad()
    package.path = package.path .. ";.\\Scripts\\?.lua;.\\Scripts\\UI\\?.lua;"
```

 becomes 

```
Terrain = require('terrain')

local function loadScratchpad()
    package.path = package.path .. ";.\\Scripts\\?.lua;.\\Scripts\\UI\\?.lua;"
```

**Comment by rkusa** [comment]
Thanks for the report and suggested fixes.

**Comment by Beamer510** [comment]
I don't have this .lua file in D:\Program Files\Eagle Dynamics\DCS World OpenBeta\Scripts\Hooks.    So, I can't add this line to it. Where else would I find it?
Sorry, Tech Cripple here.

**Comment by Beamer510** [comment]
Disregard previous post, I found it in saved games.  :)

**Comment by rkusa** [comment]
For people coming here, it has already been fixed: https://github.com/rkusa/dcs-scratchpad/releases/tag/0.6.1
