### ISSUE TITLE
Looks like 2.8 broke the LL feature.

### ISSUE THREAD

**Issue by ozdeadmeat** [rkusa/dcs-scratchpad#44]
Cant get positions anymore.

**Comment by juuba** [comment]
It's already fixed: https://github.com/rkusa/dcs-scratchpad/issues/43

Not released yet, but you can add that line manually.

**Comment by rkusa** [comment]
The fix was also released as 0.6.1 yesterday: https://github.com/rkusa/dcs-scratchpad/releases/tag/0.6.1
