### ISSUE TITLE
Coordinate Grabbing in DCS 2.8+

### ISSUE THREAD

**Issue by CaptPickguard** [rkusa/dcs-scratchpad#47]
Coordinate grabbing from the F10 map appears to be non-functional after the DCS 2.8 update.

To reproduce:
  1. Try grabbing coordinates from the DCS F10 map in the latest DCS OpenBeta version.

**Comment by rkusa** [comment]
You are probably not on the latest version, try https://github.com/rkusa/dcs-scratchpad/releases/tag/0.6.1
