### ISSUE TITLE
Where did the keyboard go?

### ISSUE THREAD

**Issue by yonygg** [rkusa/dcs-scratchpad#51]
I've been using an older version of the Scratchpad and just upgraded to the newest version (0.6.1) and Couldn't find the virtual keyboard. Where did it go?
When using VR it's the only way to actually type something on the Scratchpad other than using the L/L button.

**Comment by rkusa** [comment]
The keyboard was never part of the _official_ Scratchpad (as in the Scratchpad from this repository). It instead was added by a user and published on the DCS forum, but never updated for a newer release for the Scratchpad. I don't want to directly include the keyboard (I am blind typing in VR), but have started some work to enable others to easily at one: https://github.com/rkusa/dcs-scratchpad/pull/35
