### ISSUE TITLE
Doesn't work for me in singleplayer mode  :(. Great stuff though!

### ISSUE THREAD

**Issue by CarlosFly74** [rkusa/dcs-scratchpad#54]
Doesn't work for me in singleplayer mode. **2.8.1 Dcs version. Could this be the problem?**

**Comment by rkusa** [comment]
I assume with _Could this be the problem?_ you meant https://github.com/rkusa/dcs-scratchpad/issues/20#issuecomment-1400969316. So I am close this in favor of the discussion in the other issue.
