### ISSUE TITLE
Request to pull from .txt file via a hotkey.

### ISSUE THREAD

**Issue by Stil550** [rkusa/dcs-scratchpad#55]
Hello,  was hoping for a feature.
I'm using Scratchpad for DCS in VR, utilizing VoiceAttack.
I have VoiceAttack writing directly to a .txt file that  the Scratchpad than picks up and displays in game.
The problem seems that the scratchpad does not pull new content of the .txt file once it is changed via VoiceAttack, so I am not seeing new content that VoiceAttack writes into the file.

Was hoping for a way to refresh Scratchpad in game, to pull new content from the .txt

Thank you

**Comment by rkusa** [comment]
Scratchpad indeed only loads the contents once when you start DCS, and doesn't pick up any external changes to the files. I don't think that actively watching for file changes would be good idea (not easily done from this kind of mod). However, maybe adding an optional keyboard shortcut to trigger a reload might be a solution? Am I right to assume that you could tell VoiceAttack to hit a certain keyboard shortcut after it changed the .txt file?

**Comment by Stil550** [comment]
Yes, a simple, "refresh" button could work.  This way I can have VoiceAttack do its changes to the file itself and when needed I can hit that refresh button and pull the new content of the file into the Scratchpad's window.
And yes, it is possible to hit a hotkey via a Voiceattack.

Thank you.

**Comment by rkusa** [comment]
Added. The hotkey can be set via the `hotkeyReloadPages ` config.
