### ISSUE TITLE
Hotkeys for Left/Right are not respected in DCS 

### ISSUE THREAD

**Issue by karpiyon** [rkusa/dcs-scratchpad#57]
I set a hotkeys like this:
["hotkeyPrevPage"] = "RIGHT CTRL + RIGHT SHIFT + LWIN + A",
However, even when I press LEFT CTRL + LEFT SHIFT + LWIN + A, it still triggers the command.
Why? It should only respect RShift + RCtrl + LWin, not LShift + RShift.

Oh, and another question.
I should not share the same hotkeys I assign other sim functions, correct?

**Comment by rkusa** [comment]
DCS does not distinguish between LShift and RShift for those hotkeys – this is a limitation of DCS, so nothing I can do about it I am afraid.

> I should not share the same hotkeys I assign other sim functions, correct?
I've never tried what happens if you do, I suppose both get triggered, which could be finde depending on your use-case.
