### ISSUE TITLE
Coordinates in usable format for armament

### ISSUE THREAD

**Issue by Meistari** [rkusa/dcs-scratchpad#58]
In F-18 we need coordinates in a particular format to be input for preplanned targets. It is usually reached on the F10 map by pressing "Alt+Y" several times. The coordinates format is supposed to be XX-XX-XX.XX YYY-YY-YY.YY <- with these dashes between. But when I copy it from F10 Map it doesn't use this type of coordinates. Can it be added somehow?

**Comment by Meistari** [comment]
Hi @rkusa ,

No, it doesn't. It gives three formats (including GRID), where only two formats can be used to create a waypoint. However, none of these formats can be used to input at the TGT screen for any weapon to use in Pre-Planned mode.

Only this format can be used for the weapons, but the script doesn't provide it:

![123](https://github.com/rkusa/dcs-scratchpad/assets/88254079/fd13d3fd-8cad-475b-a9ea-8af5ee74ede2)

**Comment by rkusa** [comment]
Of the two lat/lon coordinates the Scratchpad provides, the first one is the same as the one written with the dashes - just properly written as degrees/minutes/decimal seconds. Example: mouse course is over the white dot, and the coords in the top left match the first one of the Scratchpad:

![image](https://github.com/rkusa/dcs-scratchpad/assets/409021/144b47f3-7bd6-43c2-b509-e2b16f8d90f4)

**Comment by Meistari** [comment]
> Of the two lat/lon coordinates the Scratchpad provides, the first one is the same as the one written with the dashes - just properly written as degrees/minutes/decimal seconds. Example: mouse course is over the white dot, and the coords in the top left match the first one of the Scratchpad:
> 
> ![image](https://user-images.githubusercontent.com/409021/275217545-144b47f3-7bd6-43c2-b509-e2b16f8d90f4.png)
> 
> The second lat/lon format is used for the PRECISE mode of the HSI.

I tested it today and it worked as you said. Thanks, it was confusing for me. Awesome plugin!
