### ISSUE TITLE
Content not migrated

### ISSUE THREAD

**Issue by mass2110** [rkusa/dcs-scratchpad#6]
The old content is not migrated. The savePage function in the loadConfiguration() is not called, there is not log in the scratchpadlog.

So if the new content is not migrated, the new Scratchpad directory is not created, and the pageCount = 0. If the pageCount = 0, the nextPage() function doesn't load any page, and the currentPage variable stay nil.

If the currentPage variable stay nil the futur call to savePage() just crash like that :

2019-08-23 10:13:50.038 ALERT   LUACOMMON: Error: GUI Error: [string "\Saved Games\DCS\Scripts/Hooks//scratchpad-hook.lua"]:331: attempt to call field 'savePage' (a nil value)
GUI debug.traceback: stack traceback:
	[C]: in function 'savePage'
	[string "Saved Games\DCS\Scripts/Hooks//scratchpad-hook.lua"]:331: in function 'callback'
	[string "./dxgui/bind/Widget.lua"]:330: in function <[string "./dxgui/bind/Widget.lua"]:325>

**Comment by mass2110** [comment]
Ok i just managed to make it work.

Just put the savePage() function in the scratchpad namespace, not in local, because loadConfiguration() have no acces to local function.

**Comment by rkusa** [comment]
Thanks for the report (and for looking into it and suggesting a solution)! It should be fixed now 👌
