### ISSUE TITLE
Adjusting speed of text entry?

### ISSUE THREAD

**Issue by Sting-Array** [rkusa/dcs-scratchpad#68]
Hi - is there a way to alter (slow down) the speed at which text is entered into the aircraft systems? With my FPS, the default setting for the F/A18C is causing errors between coordinates entered from the F10 map and coordinates entered into aircraft (e.g. W instead of E entries, wrong height, etc.). I am sure that these errors can be resolved if I slow down the rate of data entry. Please let me know if this is possible and how best achieved. Thanks. S

**Comment by aeronautes** [comment]
I think you're referring to the aeronautes-pit (apit) extension. If so then click the "help" button for apit and scroll towards the bottom for setitval(number) for the documentation, line 365. You can then use left mouse to highlight the commands listed under Example and click "Sel" to execute them. 

        Example:
        setitval(.2)
        loglocal(itval)  -- to see value of itval in Scratchpad.log

Start by just placing the scratchpad cursor on the "loglocal(itval) " line. Click Sel and look at your Saved Games\DCS\Logs\Scratchpad.log file to see the results. It should show .1. Next adjust the number in "setitval(.2)" of the Example to .3 and click "Sel". Execute the loglocal to see it's value is set as you expect. Now test that by clicking "LatLon" button to see if it works. Repeat those steps until you find a value that you're happy with. 

These steps work for your current session but will revert to the default on your next restart of DCS. To make it persistent you'll need to edit the appropriate source file. If you want this value only for F18 then edit Saved Games\DCS\Scripts\Scratchpad\Extensions\aeronautes-lib\FA-18C_hornet.lua. Make a line like this anywhere  below the "local ft = {}" command:

ft.init = [[ setitval(xxx) ]]

Change the xxx to the number you found previously. Save the file. If you're still in DCS you can verify this works by clicking on the "modload" button. This will reread the FA-18C_hornet.lua file and execute it's contents. 

If you want this itval to be the default across all modules then you'll need to edit the Saved Games\DCS\Scripts\Scratchpad\Extensions\aeronautes-pit.lua file. At line 473 you should find:

local itval = 0.1               -- default input delay

Change that to the number you found in the Example steps above. Save it and restart DCS.
Let me know how your experience went and what you chose to do. I've had this extension tested by several people and this is the first time this issue has come up. I'd like to know how common it is.

**Comment by Sting-Array** [comment]
Thanks for your help with this. Your advice has led me to a solution. I really appreciate your willingness to take time to support me in resolving this issue. Regards. S

**Comment by Sting-Array** [comment]
Thanks for your help with this. Your advice has led me to a solution. I really appreciate your willingness to take time to support me in resolving this issue. Regards. S
