### ISSUE TITLE
Outputting only DMS precision coordinates?

### ISSUE THREAD

**Issue by Gil80** [rkusa/dcs-scratchpad#69]
Hi,
Is it possible to only output DMS precision coordinates in the text area, instead of all the other formats?

**Comment by rkusa** [comment]
You'd have to change the copy of your mod. If you replace [those lines](https://github.com/rkusa/dcs-scratchpad/blob/main/Scripts/Hooks/scratchpad-hook.lua#L627-L654) with `return {DMS = true, DDM = false, MGRS = false}`, you should get the desired result.

**Comment by Gil80** [comment]
Thank you.

Lastly, is it possible to use this add on to automatically insert the coordinates via UFC in the F18?

**Comment by rkusa** [comment]
> Lastly, is it possible to use this add on to automatically insert the coordinates via UFC in the F18?

Yes, @aeronautes created a plugin for that. At the top of the plugin script, there is a install and usage documentation: https://github.com/rkusa/dcs-scratchpad/blob/main/Scripts/Scratchpad/Extensions/Disabled/aeronautes-pit.lua

**Comment by Gil80** [comment]
> > Lastly, is it possible to use this add on to automatically insert the coordinates via UFC in the F18?
> 
> Yes, @aeronautes created a plugin for that. At the top of the plugin script, there is a install and usage documentation: https://github.com/rkusa/dcs-scratchpad/blob/main/Scripts/Scratchpad/Extensions/Disabled/aeronautes-pit.lua

Sorry to bother you once again. I tried to use it but it doesn't seem to input the correct coordinates.
Do I need to be in precise mode or some other f18 config for this plugin to work?

![Untitled-1](https://github.com/user-attachments/assets/099d9918-9c97-44fb-9276-c3678a11bac8)

**Comment by rkusa** [comment]
@Gil80 I personally haven't used this mod yet so I cannot help. Maybe check the forum thread about the Scratchpad it looks like it has some conversations about the mod: https://forum.dcs.world/topic/195700-in-game-scratchpad-mod-available-works-great-in-vr/page/32/

**Comment by aeronautes** [comment]
Yes it assumes precise mode so if you're self starting or using system assigned autostart then you'll need to manually set precise. Alternatlively if you use the apit start button, that will set precise for you. Unfortunately there's not a way for lua to directly query the status of cockpit systems such as MFD states without going through the Exports.lua interface. I'm hesitating to do so as there are coordination issues with other mods that use Exports. It would however allow access to many settings and values of cockpit systems. Maybe in the future.
________________________________
